// MusicData.js
export const songs = [
  {
    id: 1,
    title: "Shape of You",
    artist: "Ed Sheeran",
    genre: "Pop",
    year: 2017,
    duration: "3:53",
  },
  {
    id: 2,
    title: "Blinding Lights",
    artist: "The Weeknd",
    genre: "Pop/R&B",
    year: 2020,
    duration: "3:20",
  },
  {
    id: 3,
    title: "Someone Like You",
    artist: "Adele",
    genre: "Pop",
    year: 2011,
    duration: "4:45",
  },
  {
    id: 4,
    title: "Bad Guy",
    artist: "Billie Eilish",
    genre: "Pop",
    year: 2019,
    duration: "3:14",
  },
  {
    id: 5,
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    genre: "Pop/Funk",
    year: 2014,
    duration: "4:30",
  },
  {
    id: 6,
    title: "Despacito",
    artist: "Luis Fonsi & Daddy Yankee",
    genre: "Reggaeton",
    year: 2017,
    duration: "3:48",
  },
  {
    id: 7,
    title: "God's Plan",
    artist: "Drake",
    genre: "Hip Hop",
    year: 2018,
    duration: "3:18",
  },
  {
    id: 8,
    title: "Rolling in the Deep",
    artist: "Adele",
    genre: "Pop",
    year: 2011,
    duration: "3:48",
  },
  {
    id: 9,
    title: "Dynamite",
    artist: "BTS",
    genre: "K-Pop",
    year: 2020,
    duration: "3:19",
  },
  {
    id: 10,
    title: "Stay With Me",
    artist: "Sam Smith",
    genre: "Pop",
    year: 2014,
    duration: "2:53",
  },
  {
    id: 11,
    title: "Dance Monkey",
    artist: "Tones and I",
    genre: "Pop",
    year: 2019,
    duration: "3:29",
  },
  {
    id: 12,
    title: "Sunflower",
    artist: "Post Malone & Swae Lee",
    genre: "Hip Hop/Pop",
    year: 2018,
    duration: "2:38",
  },
  {
    id: 13,
    title: "Closer",
    artist: "The Chainsmokers ft. Halsey",
    genre: "Electronic/Pop",
    year: 2016,
    duration: "4:05",
  },
  {
    id: 14,
    title: "Shallow",
    artist: "Lady Gaga & Bradley Cooper",
    genre: "Pop",
    year: 2018,
    duration: "3:36",
  },
  {
    id: 15,
    title: "Havana",
    artist: "Camila Cabello ft. Young Thug",
    genre: "Pop",
    year: 2017,
    duration: "3:37",
  },
  {
    id: 16,
    title: "Shake It Off",
    artist: "Taylor Swift",
    genre: "Pop",
    year: 2014,
    duration: "3:39",
  },
  {
    id: 17,
    title: "Perfect",
    artist: "Ed Sheeran",
    genre: "Pop",
    year: 2017,
    duration: "4:23",
  },
  {
    id: 18,
    title: "Old Town Road",
    artist: "Lil Nas X",
    genre: "Hip Hop/Country",
    year: 2019,
    duration: "2:37",
  },
  {
    id: 19,
    title: "Don't Start Now",
    artist: "Dua Lipa",
    genre: "Pop",
    year: 2019,
    duration: "3:03",
  },
  {
    id: 20,
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    genre: "Pop",
    year: 2020,
    duration: "2:54",
  },
  {
    id: 21,
    title: "7 Rings",
    artist: "Ariana Grande",
    genre: "Pop/R&B",
    year: 2019,
    duration: "2:58",
  },
  {
    id: 22,
    title: "Say So",
    artist: "Doja Cat",
    genre: "Pop/R&B",
    year: 2020,
    duration: "3:57",
  },
  {
    id: 23,
    title: "Circles",
    artist: "Post Malone",
    genre: "Pop/Rock",
    year: 2019,
    duration: "3:35",
  },
  {
    id: 24,
    title: "Mood",
    artist: "24kGoldn ft. iann dior",
    genre: "Hip Hop/Rock",
    year: 2020,
    duration: "2:21",
  },
  {
    id: 25,
    title: "Good 4 U",
    artist: "Olivia Rodrigo",
    genre: "Pop/Rock",
    year: 2021,
    duration: "2:58",
  },
  {
    id: 26,
    title: "drivers license",
    artist: "Olivia Rodrigo",
    genre: "Pop",
    year: 2021,
    duration: "4:02",
  },
  {
    id: 27,
    title: "Leave The Door Open",
    artist: "Silk Sonic",
    genre: "R&B",
    year: 2021,
    duration: "3:47",
  },
  {
    id: 28,
    title: "Stay",
    artist: "The Kid LAROI & Justin Bieber",
    genre: "Pop",
    year: 2021,
    duration: "2:21",
  },
  {
    id: 29,
    title: "Levitating",
    artist: "Dua Lipa",
    genre: "Pop",
    year: 2020,
    duration: "3:23",
  },
  {
    id: 30,
    title: "Save Your Tears",
    artist: "The Weeknd",
    genre: "Pop/R&B",
    year: 2020,
    duration: "3:35",
  },
  {
    id: 31,
    title: "Butter",
    artist: "BTS",
    genre: "K-Pop",
    year: 2021,
    duration: "2:44",
  },
  {
    id: 32,
    title: "Heat Waves",
    artist: "Glass Animals",
    genre: "Indie/Pop",
    year: 2020,
    duration: "3:59",
  },
  {
    id: 33,
    title: "Kiss Me More",
    artist: "Doja Cat ft. SZA",
    genre: "Pop/R&B",
    year: 2021,
    duration: "3:28",
  },
  {
    id: 34,
    title: "Montero",
    artist: "Lil Nas X",
    genre: "Hip Hop/Pop",
    year: 2021,
    duration: "2:17",
  },
  {
    id: 35,
    title: "Peaches",
    artist: "Justin Bieber ft. Daniel Caesar",
    genre: "R&B/Pop",
    year: 2021,
    duration: "3:18",
  },
  {
    id: 36,
    title: "positions",
    artist: "Ariana Grande",
    genre: "Pop/R&B",
    year: 2020,
    duration: "2:52",
  },
  {
    id: 37,
    title: "Therefore I Am",
    artist: "Billie Eilish",
    genre: "Pop",
    year: 2020,
    duration: "2:54",
  },
  {
    id: 38,
    title: "Astronaut In The Ocean",
    artist: "Masked Wolf",
    genre: "Hip Hop",
    year: 2021,
    duration: "2:12",
  },
  {
    id: 39,
    title: "34+35",
    artist: "Ariana Grande",
    genre: "Pop/R&B",
    year: 2020,
    duration: "2:53",
  },
  {
    id: 40,
    title: "Without You",
    artist: "The Kid LAROI",
    genre: "Pop",
    year: 2020,
    duration: "2:41",
  },
  {
    id: 41,
    title: "Deja Vu",
    artist: "Olivia Rodrigo",
    genre: "Pop/Rock",
    year: 2021,
    duration: "3:35",
  },
  {
    id: 42,
    title: "Willow",
    artist: "Taylor Swift",
    genre: "Pop/Folk",
    year: 2020,
    duration: "3:34",
  },
  {
    id: 43,
    title: "What You Know Bout Love",
    artist: "Pop Smoke",
    genre: "Hip Hop",
    year: 2020,
    duration: "2:44",
  },
  {
    id: 44,
    title: "Anyone",
    artist: "Justin Bieber",
    genre: "Pop",
    year: 2021,
    duration: "3:10",
  },
  {
    id: 45,
    title: "My Ex's Best Friend",
    artist: "Machine Gun Kelly & blackbear",
    genre: "Pop/Rock",
    year: 2020,
    duration: "2:15",
  },
  {
    id: 46,
    title: "Streets",
    artist: "Doja Cat",
    genre: "R&B/Pop",
    year: 2021,
    duration: "3:47",
  },
  {
    id: 47,
    title: "Bang!",
    artist: "AJR",
    genre: "Pop/Rock",
    year: 2020,
    duration: "2:50",
  },
  {
    id: 48,
    title: "Beautiful Mistakes",
    artist: "Maroon 5 ft. Megan Thee Stallion",
    genre: "Pop",
    year: 2021,
    duration: "3:47",
  },
  {
    id: 49,
    title: "Mood Swings",
    artist: "Pop Smoke ft. Lil Tjay",
    genre: "Hip Hop",
    year: 2020,
    duration: "3:31",
  },
  {
    id: 50,
    title: "Better Days",
    artist: "NEIKED x Mae Muller x Polo G",
    genre: "Pop",
    year: 2021,
    duration: "2:42",
  },
];
